export const characters = [
  // Personagens Principais
  {
    id: 1,
    name: "Tanjiro Kamado",
    image: "/placeholder.svg?width=300&height=400",
    bio: "Um jovem bondoso que se torna um Caçador de Demônios para vingar sua família e encontrar uma cura para sua irmã, Nezuko.",
    affiliation: "Caçador de Demônios",
    breathing: "Respiração da Água e Hinokami Kagura",
    trivia: "Possui um olfato extremamente aguçado, capaz de sentir a presença de demônios e emoções.",
  },
  {
    id: 2,
    name: "Nezuko Kamado",
    image: "/placeholder.svg?width=300&height=400",
    bio: "A irmã mais nova de Tanjiro, transformada em um demônio. Ela luta para proteger os humanos e resiste à necessidade de consumir sangue.",
    affiliation: "Demônio",
    breathing: "Kekkijutsu (Arte Demoníaca de Sangue)",
    trivia: "Consegue alterar o tamanho de seu corpo e possui uma força regenerativa impressionante.",
  },
  {
    id: 3,
    name: "Zenitsu Agatsuma",
    image: "/placeholder.svg?width=300&height=400",
    bio: "Um Caçador de Demônios medroso que só consegue lutar quando está inconsciente ou dormindo, revelando um poder imenso.",
    affiliation: "Caçador de Demônios",
    breathing: "Respiração do Trovão",
    trivia: "Sua audição é sobre-humana, permitindo que ele distinga o som do coração de pessoas e demônios.",
  },
  {
    id: 4,
    name: "Inosuke Hashibira",
    image: "/placeholder.svg?width=300&height=400",
    bio: "Criado por javalis nas montanhas, Inosuke é um lutador selvagem e orgulhoso, com um estilo de luta único e imprevisível.",
    affiliation: "Caçador de Demônios",
    breathing: "Respiração da Besta",
    trivia: "Usa uma máscara de javali para esconder seu rosto surpreendentemente delicado.",
  },
  // Hashiras
  {
    id: 5,
    name: "Giyu Tomioka",
    image: "/placeholder.svg?width=300&height=400",
    bio: "O Hashira da Água. Um espadachim poderoso e reservado que foi o primeiro a encontrar Tanjiro e Nezuko após a tragédia.",
    affiliation: "Hashira da Água",
    breathing: "Respiração da Água",
    trivia: "Criou a décima primeira forma da Respiração da Água, chamada 'Calmaria'.",
  },
  {
    id: 6,
    name: "Shinobu Kocho",
    image: "/placeholder.svg?width=300&height=400",
    bio: "A Hashira do Inseto. Apesar de sua aparência calma e amigável, ela é extremamente letal, usando venenos para derrotar demônios.",
    affiliation: "Hashira do Inseto",
    breathing: "Respiração do Inseto",
    trivia: "É a única Hashira que não consegue decapitar um demônio, compensando com sua agilidade e venenos mortais.",
  },
  {
    id: 7,
    name: "Kyojuro Rengoku",
    image: "/placeholder.svg?width=300&height=400",
    bio: "O Hashira das Chamas. Um guerreiro carismático e otimista com um inabalável senso de dever e justiça.",
    affiliation: "Hashira das Chamas",
    breathing: "Respiração das Chamas",
    trivia: "Sua paixão por comida é quase tão grande quanto sua paixão por proteger os inocentes.",
  },
  {
    id: 8,
    name: "Tengen Uzui",
    image: "/placeholder.svg?width=300&height=400",
    bio: "O Hashira do Som. Um ex-shinobi extravagante que valoriza tudo que é 'chamativo'. Luta com duas lâminas Nichirin gigantes.",
    affiliation: "Hashira do Som",
    breathing: "Respiração do Som",
    trivia: "Possui três esposas, todas kunoichis habilidosas que o auxiliam em suas missões.",
  },
  {
    id: 9,
    name: "Muichiro Tokito",
    image: "/placeholder.svg?width=300&height=400",
    bio: "O Hashira da Névoa. Um jovem prodígio que parece distraído, mas é um dos espadachins mais talentosos da corporação.",
    affiliation: "Hashira da Névoa",
    breathing: "Respiração da Névoa",
    trivia: "Tornou-se um Hashira apenas dois meses após pegar em uma espada pela primeira vez.",
  },
  {
    id: 10,
    name: "Mitsuri Kanroji",
    image: "/placeholder.svg?width=300&height=400",
    bio: "A Hashira do Amor. Entrou para os Caçadores de Demônios para encontrar um marido mais forte que ela. É incrivelmente forte e flexível.",
    affiliation: "Hashira do Amor",
    breathing: "Respiração do Amor",
    trivia: "Sua espada é flexível como um chicote, uma arma que só ela consegue manejar.",
  },
  {
    id: 11,
    name: "Gyomei Himejima",
    image: "/placeholder.svg?width=300&height=400",
    bio: "O Hashira da Pedra. Considerado o mais forte entre os Hashiras. É um gigante gentil e cego que está sempre em oração.",
    affiliation: "Hashira da Pedra",
    breathing: "Respiração da Pedra",
    trivia: "Luta com um mangual e um machado conectados por uma corrente, armas extremamente difíceis de dominar.",
  },
  {
    id: 12,
    name: "Sanemi Shinazugawa",
    image: "/placeholder.svg?width=300&height=400",
    bio: "O Hashira do Vento. Agressivo e de pavio curto, seu corpo é coberto de cicatrizes e seu ódio por demônios é incomparável.",
    affiliation: "Hashira do Vento",
    breathing: "Respiração do Vento",
    trivia: "Seu sangue é 'Marechi', um tipo sanguíneo raro que é extremamente intoxicante para demônios.",
  },
  {
    id: 13,
    name: "Obanai Iguro",
    image: "/placeholder.svg?width=300&height=400",
    bio: "O Hashira da Serpente. Um espadachim rigoroso e misterioso, sempre acompanhado por sua serpente, Kaburamaru.",
    affiliation: "Hashira da Serpente",
    breathing: "Respiração da Serpente",
    trivia: "Kaburamaru, sua serpente, o ajuda em combate, lendo os ataques do inimigo.",
  },
  // Luas Superiores
  {
    id: 14,
    name: "Kokushibo",
    image: "/placeholder.svg?width=300&height=400",
    bio: "Lua Superior Um. O demônio mais poderoso sob o comando de Muzan, foi um Caçador de Demônios na era de ouro.",
    affiliation: "Lua Superior Um",
    breathing: "Respiração da Lua",
    trivia: "É o irmão gêmeo de Yoriichi Tsugikuni, o criador da primeira respiração, a Respiração do Sol.",
  },
  {
    id: 15,
    name: "Doma",
    image: "/placeholder.svg?width=300&height=400",
    bio: "Lua Superior Dois. Um demônio sádico e sem emoções que lidera um culto para devorar suas seguidoras.",
    affiliation: "Lua Superior Dois",
    breathing: "Kekkijutsu de Gelo",
    trivia: "Foi o demônio que matou a irmã de Shinobu e a mãe de Inosuke.",
  },
  {
    id: 16,
    name: "Akaza",
    image: "/placeholder.svg?width=300&height=400",
    bio: "Lua Superior Três. Um mestre em artes marciais que busca a perfeição no combate e despreza os fracos.",
    affiliation: "Lua Superior Três",
    breathing: "Kekkijutsu de Combate",
    trivia: "Por respeito à sua vida humana, ele se recusa a lutar, matar ou devorar mulheres.",
  },
  // ... (outros personagens)
  {
    id: 17,
    name: "Muzan Kibutsuji",
    image: "/placeholder.svg?width=300&height=400",
    bio: "O Rei dos Demônios e o progenitor de todos os outros. É o principal antagonista, buscando a imortalidade perfeita.",
    affiliation: "Rei dos Demônios",
    breathing: "Origem dos Demônios",
    trivia: "Pode alterar sua aparência, gênero e idade à vontade para se esconder na sociedade humana.",
  },
  {
    id: 18,
    name: "Genya Shinazugawa",
    image: "/placeholder.svg?width=300&height=400",
    bio: "Irmão mais novo de Sanemi. Não consegue usar Respirações, mas pode ganhar poder demoníaco ao devorar demônios.",
    affiliation: "Caçador de Demônios",
    breathing: "Nenhuma (Usa armas de fogo e poder demoníaco)",
    trivia: "Sua capacidade de assimilação demoníaca é única entre os caçadores.",
  },
  {
    id: 19,
    name: "Sakonji Urokodaki",
    image: "/placeholder.svg?width=300&height=400",
    bio: "Ex-Hashira da Água e mestre de Tanjiro e Giyu. Usa uma máscara de tengu para esconder seu rosto gentil.",
    affiliation: "Treinador / Ex-Hashira",
    breathing: "Respiração da Água",
    trivia: "Todos os seus alunos usam máscaras de raposa esculpidas por ele como amuleto de proteção.",
  },
  {
    id: 20,
    name: "Tamayo",
    image: "/placeholder.svg?width=300&height=400",
    bio: "Uma demônio médica que se libertou do controle de Muzan e dedica sua existência a encontrar uma cura e derrotá-lo.",
    affiliation: "Demônio Aliada",
    breathing: "Kekkijutsu de Encantamento Sanguíneo",
    trivia: "Modificou seu corpo e o de Yushiro para sobreviver com uma quantidade mínima de sangue humano.",
  },
  {
    id: 21,
    name: "Yushiro",
    image: "/placeholder.svg?width=300&height=400",
    bio: "O leal assistente de Tamayo, transformado por ela para ser salvo de uma doença terminal. É extremamente protetor com ela.",
    affiliation: "Demônio Aliado",
    breathing: "Kekkijutsu de Ocultação",
    trivia:
      "Sua arte demoníaca permite que ele oculte ou revele a presença de pessoas e objetos usando talismãs de papel.",
  },
  {
    id: 22,
    name: "Rui",
    image: "/placeholder.svg?width=300&height=400",
    bio: "Lua Inferior Cinco. Um demônio que ansiava por laços familiares e criou uma 'família' forçada na Montanha Natagumo.",
    affiliation: "Lua Inferior Cinco",
    breathing: "Kekkijutsu de Teias",
    trivia: "Recebeu uma grande quantidade de sangue de Muzan, tornando-o tão forte quanto uma Lua Superior.",
  },
]

export const seasons = [
  {
    id: 1,
    seasonNumber: 1,
    title: "Temporada 1: A Jornada de Tanjiro Kamado",
    episodes: [
      {
        epNumber: 1,
        title: "Crueldade",
        image: "/placeholder.svg?width=400&height=225",
        summary:
          "A vida de Tanjiro Kamado muda para sempre quando sua família é massacrada por um demônio e sua irmã Nezuko é transformada.",
      },
      {
        epNumber: 2,
        title: "Sakonji Urokodaki, o Treinador",
        image: "/placeholder.svg?width=400&height=225",
        summary:
          "Seguindo o conselho de Giyu, Tanjiro viaja para o Monte Sagiri para encontrar um treinador que possa prepará-lo para a Seleção Final.",
      },
    ],
  },
  {
    id: 2,
    seasonNumber: 2,
    title: "Temporada 2: Arco do Trem Infinito e Distrito do Entretenimento",
    episodes: [
      {
        epNumber: 1,
        title: "Hashira das Chamas, Kyojuro Rengoku",
        image: "/placeholder.svg?width=400&height=225",
        summary:
          "Tanjiro, Nezuko, Zenitsu e Inosuke embarcam no Trem Infinito para investigar uma série de desaparecimentos misteriosos.",
      },
      {
        epNumber: 8,
        title: "Hashira do Som, Tengen Uzui",
        image: "/placeholder.svg?width=400&height=225",
        summary:
          "A missão agora é no Distrito do Entretenimento, onde o extravagante Hashira do Som, Tengen Uzui, precisa de ajuda para encontrar suas esposas.",
      },
    ],
  },
  {
    id: 3,
    seasonNumber: 3,
    title: "Temporada 3: Arco da Vila dos Ferreiros",
    episodes: [
      {
        epNumber: 1,
        title: "O Sonho de Alguém",
        image: "/placeholder.svg?width=400&height=225",
        summary:
          "Tanjiro viaja para a Vila dos Ferreiros para consertar sua espada e acaba se envolvendo em uma batalha contra duas Luas Superiores.",
      },
    ],
  },
  {
    id: 4,
    seasonNumber: 4,
    title: "Temporada 4: Arco do Treinamento dos Hashiras",
    episodes: [
      {
        epNumber: 1,
        title: "Para Derrotar Muzan Kibutsuji",
        image: "/placeholder.svg?width=400&height=225",
        summary:
          "Os Hashiras se reúnem para iniciar um treinamento intensivo com todos os Caçadores de Demônios, visando fortalecer suas forças para a batalha final.",
      },
    ],
  },
]
